server:
  port: ${NORA_PORT:18081}

spring:
  jackson:
    time-zone: Asia/Shanghai
  application:
    name: file-service
  datasource:
    url: ${NORA_DB_URL:jdbc:postgresql://localhost:15432/nora?currentSchema=schema_file}
    username: nora
    password: nora
  flyway:
    enabled: true
    schemas: schema_file
    default-schema: schema_file
    create-schemas: true
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${NORA_NACOS_SERVER:localhost:18848}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

nora:
  timezone: Asia/Shanghai
  file:
    storage-dir: ./data/files/
  rag:
    base-url: ${NORA_RAG_URL:http://localhost:18082}

management:
  endpoints:
    web:
      exposure:
        include: health

