server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        enabled: true
    gateway:
      routes:
        - id: agent
          uri: lb://agent-service
          predicates:
            - Path=/api/chat/**
        - id: models
          uri: lb://agent-service
          predicates:
            - Path=/api/models/**
        - id: file
          uri: lb://file-service
          predicates:
            - Path=/api/files/**
        - id: rag
          uri: lb://rag-service
          predicates:
            - Path=/api/rag/**
        - id: datasources
          uri: lb://datasource-service
          predicates:
            - Path=/api/datasources/**
        - id: automations
          uri: lb://automation-service
          predicates:
            - Path=/api/automations/**

management:
  endpoints:
    web:
      exposure:
        include: health
