server:
  port: 8086

spring:
  jackson:
    time-zone: Asia/Shanghai
  application:
    name: automation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nora?currentSchema=schema_automation
    username: nora
    password: nora
  flyway:
    enabled: true
    schemas: schema_automation
    default-schema: schema_automation
    create-schemas: true
  cloud:
    nacos:
      discovery:
        enabled: true

nora:
  timezone: Asia/Shanghai
  datasource:
    base-url: http://localhost:8084
  agent:
    base-url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: health
