server:
  port: 8086

spring:
  application:
    name: automation-service
  cloud:
    nacos:
      discovery:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
